# Generated by Django 4.1.3 on 2022-11-24 18:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StationControlApp', '0002_alter_station_time_broken_alter_station_x_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='time_broken',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 8, 7, 52, 75999), editable=False),
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(choices=[('1', 'x'), ('2', 'y'), ('3', 'z')], default='x', max_length=2)),
                ('distance', models.IntegerField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
