# Generated by Django 4.1.3 on 2022-11-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationControlApp', '0003_alter_station_time_broken_indication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='time_broken',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
